### ISSUE TITLE
Google Contacts app allows contacts to be added to base EteSync account

### ISSUE THREAD

**Issue by troyalmeida** [etesync/android#151]
Device: Pixel 3 running Android 11, build RP1A.201005.004

The default contacts app for the Pixel 3 is the one that Google provides in the Play Store.  I'm using the latest version (v3.34.3.338741632) of that app at the time of this writing.

https://play.google.com/store/apps/details?id=com.google.android.contacts

When I click the Account button in the top right corner so I can toggle accounts, I have these options:

1. Contacts from all accounts
2. Google account x
3. Google account y
4. Google account z
5. EteSync - _username_
6. EteSync Address Book - _collection x_
7. EteSync Address Book - _collection y_
8. EteSync Address Book - _collection z_

The base EteSync account (account 5 above) should not show up in this list, as it is not an Address Book at all.  The app _does_ allow contacts to be added to that account, although the EteSync client will never sync them anywhere.

I've already reached out to Tom about this.  He thinks it may be related to an earlier Android 11 issue when contacts were being set as read only and unable to edit.

Thanks!

Troy

**Comment by 60Eight** [comment]
Hi @tasn. Even I'm facing the similar problem.

The base account is also listed when I click on Account button in Google Contacts app.
Additionally, there's a major problem that, there's no option to add/update/delete any contacts under any of the EteSync accounts.

**Device**: Pixel 3
**Android version**: 11
**Android build**: RQ1A.210105.003
**Google Contacts version**: 3.36.3.246104542

**Comment by tasn** [comment]
This is so annoying as it doesn't happen with other apps. I just checked and I can confirm I see it with the Google contacts apps, but I don't see it with other apps.
I'm still unsure about how to best solve this though, and if we should even do anything, or if it's a bug in Google contacts.
We could show an error when people save contacts to this account to prevent accidental use, though it's not perfect.

**Comment by 60Eight** [comment]
@tasn, I believe an error in the meantime would be a good step. Did you have any luck with the other problem of not being able to edit any contacts at all?

**Comment by tasn** [comment]
Remind me? I thought all the issues have been resolved.

**Comment by troyalmeida** [comment]
Several months back, I had reported (via email) the same issue of not being able to edit EteSync contacts on Android 11, but @tasn promptly fixed that one. So for me, that one is all set.

But this issue #151 is still happening for me.  I just ignore it at this point because I know what's happening, but an error to the user would be a good stopgap measure to prevent others from saving to that account.

I always think of my wife with this stuff... she doesn't care how something works, just that it does work.  She could easily save into the EteSync base account and have no idea anything was wrong.  So an error message could go a long way for many users.

**Comment by 60Eight** [comment]
> Several months back, I had reported (via email) the same issue of not being able to edit EteSync contacts on Android 11, but @tasn promptly fixed that one. So for me, that one is all set.

@tasn I'm still having this problem.

**Comment by tasn** [comment]
After chatting with @60Eight, it seems like he's using the latest Jan update by Google. @troyalmeida, have you also updated?
I realise we are mixing two different issues here. The problem @60Eight is that he can't edit contacts at all.

**Comment by 60Eight** [comment]
@tasn Sorry for bothering. I think I figured out the reason.

I had revoked all the permissions (that were possible to be revoked) from Google Play Services app some time back. Re-enabled them now to fix it.

**Comment by tasn** [comment]
No worries, just glad it's solved and the solution is now listed here. OK, now back to the original issue.

**Comment by mbiebl** [comment]
Just wondering, whether you have found a solution for this? 
This appears to be a regression/changed behaviour in the Google Contacts app. Older versions like  Google Contacts_v3.29.1.324588640 do not show this problem.

Related https://forums.bitfire.at/topic/2399/google-contacts-shows-non-address-book-account

**Comment by tasn** [comment]
Yeah that's a new pain due to a bug in the Google contacts app. :(
I have no workaround in mind, I don't know if one is even possible. There was another Google contacts bug that we managed to workaround before, but for this, I really don't know.

**Comment by mbiebl** [comment]
Good news.
Apparently this has been fixed in the latest version of Google Contacts, i.e. 3.39.1.356372497

**Comment by troyalmeida** [comment]
Looks great on my end now too!!

**Comment by tasn** [comment]
Yay, thanks for letting us know!! :tada:
