### ISSUE TITLE
Unable to sync etesync 2.0 tasks to tasks.org

### ISSUE THREAD

**Issue by Nurtyll** [etesync/android#162]
I moved my tasks to etesync 2.0 - the etesync android app recognizes the account and the lists but I am unable to sync them with tasks.org and opentasks. The username and tasklists are shown, but no tasks are synchronized. I can add tasks and sync them from the app to the server but I cannot sync tasks from etesync to my phone.

When I use the webapp on mac, I am able to see the tasks.

Since I was not able to sync the tasks to both apps, I figured the problem could be with etesync and not opentasks or tasks.org

I am using Fairphone Open 19.11.2 (Android 7.1.2) and the latest app versions from F-Droid.

Thank you for your help!

**Comment by tasn** [comment]
Can you maybe try the following:
1. Uninstall OpenTasks and EteSync
2. Install EteSync back
3. Add your account to the EteSync app

Do things show in Tasks.org?

**Comment by Nurtyll** [comment]
Thank you very much, that did the trick. After reinstalling both apps and setting up the EteSync account, the EteSync-app asked for permission to sync data with tasks.org and now it is working!
Have a nice day!

**Comment by tasn** [comment]
Great, I figured it was probably just an issue with the apps not detecting eachother. :)

Btw, don't install OpenTasks, or if you want to, first set "Prefer Tasks.org" in the EteSync app, and only then install.

**Comment by Nurtyll** [comment]
Hi again,

I installed the update, etesync is now version 2.2.1. The tasks kept visible for approximately one day until I edited one task inside the [web interface](https://pim.etesync.com). After etesync synced, because it detected a change, only this one edited task appeared inside the tasks.org app. Now I tried reinstalling both apps and since the fresh installation, no task is shown inside the app (at first, all tasks get synced and, I think after some time etesync is checking for changes and then the task list is empty again...)

Thanks for your help!

**Comment by tasn** [comment]
Are you on the latest version of Tasks.org too? Btw, 2.2.1 is *not* the latest etesync version.

**Comment by Nurtyll** [comment]
Ok, Google Play Store and F-Droid currently offer etesync version 2.2.1. I have tasks.org at version 10.4.1, also latest version in both stores...

**Comment by tasn** [comment]
Sorry, I misread it as 2.1.2. :P 

Interesting then that it's happening then (it works here). Do you see the task list in tasks.org's list of sources? (see the menu on the left).
Do you have opentasks installed?

**Comment by Nurtyll** [comment]
Haha no problem.

Yes, I can see the account name and my three task lists but they contain no tasks...

Nope, only tasks.org installed...

**Comment by tasn** [comment]
Do the collections contain tasks in the etesync app?
How about the web app?

**Comment by Nurtyll** [comment]
I can see the tasks within the etesync app. The change journal shows everything correctly and when I click on the task I can see it.
The [web app](
https://pim.etesync.com/) works fine.

**Comment by tasn** [comment]
Can you try using OpenTasks just to see if it works? I wonder if it's a tasks.org issue or an etesync one.

**Comment by Nurtyll** [comment]
Good morning!
Sure! I uninstalled tasks.org and installed OpenTasks (you mentioned it's not good to use both apps at the same time), granted the permissions inside etesync and OpenTasks - same problem as in tasks.org. I see the task lists but there are no tasks inside.
Thanks for your perseverance ;)

**Comment by tasn** [comment]
Ahhhhh, damn. :( 
I wonder what it could be, I really have no idea. I'm going to try to figure it out this week, but please remind me if you don't hear back.

Thanks, and sorry for the trouble!

**Comment by Nurtyll** [comment]
Hi. I'm still not able to view tasks in tasks.org after the latest updates. The versions are:
tasks.org: 11.1
etesync: 2.2.3

Hope you had a restful Christmas. Happy New Year and thanks for the help!

**Comment by tasn** [comment]
A bit of the nuclear option: try to uninstall and reinstall both apps (make sure that you are aware of any data that hasn't synced so it's not deleted). I think it should be fixed now that both apps are fixed. Especially given your report that web -> tasks.org works.

Another thing that could be happening (maybe worth checking before you do the above): the tasks.org UI can be a bit confusing. Make sure that you set the task to be saved to etesync rather than local task list. Please check this before removing as instructed above.

Sorry for the trouble.

**Comment by Nurtyll** [comment]
Web - > tasks.org works only for the task I edited inside the web interface (I have multiple tasks inside the web interface) And it disappeared after some time, I think maybe after a new sync, as I mentioned in the other issue. 

The tasks are synced inside the correct list. I'm aware, that tasks.org has local and synced lists. 

Ok, I'll try reinstalling.

**Comment by Nurtyll** [comment]
Good morning!

I reinstalled both apps and the behaviour was not different than usual: first sync was successful. All tasks were displayed, just like in the webapp, also within tasks.org on the cell phone. And as soon as a (forced by user) second sync is done, all tasks disappear in tasks.org.

Thank you again and a happy new year :)

**Comment by Nurtyll** [comment]
Hi. Are there any news? I'm still not able to view the tasks on my phone. I really want to use the tasks app, because I tend to loose my notes written down on paper ^^ and I cannot use tasks.org without etesync - there is no local tasklist...

**Comment by tasn** [comment]
Thanks for following up, I don't know how I missed your reply. As for your issue: I still don't get what's going 

Side note: tasks.org does have a local task list you can use until this is fixed.

@abaker, any tips on how to get information from the Tasks.org side so I know what EteSync is doing wrong?

**Comment by Nurtyll** [comment]
No worries :) Thank you for your help.

**Comment by abaker** [comment]
I've been following this thread but I'm not sure what is going on. There is not much in terms of diagnostics in tasks.org, you would have to install a debug build to inspect the database

@Nurtyll can you update Tasks.org to v11.2.1 and try again? Prior to this version Tasks wasn't displaying error messages for EteSync app sync. After updating and attempting to sync there will be an error indicator in the navigation drawer if there was an exception

**Comment by tasn** [comment]
Thanks a lot @abaker for being so on it!

Assuming (I hope) that EteSync doesn't instruct tasks.org to wipe everything, what do you think it could be? What could cause tasks to remove everything? Maybe we are making tasks.org think we are recreating the collection for whatever reason (similar to the sync id issue from before).

**Comment by abaker** [comment]
Tasks.org's OpenTask sync is not very robust. If any of the batch operations fail it errors out and retries later. If things are truly borked the retry will fail and retry ad infinitum.

Tasks checks for deletions by [querying for Task._UIDs](https://github.com/tasks/tasks/blob/d3c06fd32376dc28e4b3d1e5f9987b2732d2c8c1/app/src/main/java/org/tasks/data/OpenTaskDao.kt#L62), then comparing uids in the content provider vs its own database [here](https://github.com/tasks/tasks/blob/d3c06fd32376dc28e4b3d1e5f9987b2732d2c8c1/app/src/main/java/org/tasks/opentasks/OpenTasksSynchronizer.kt#L192). So if tasks are all disappearing at once then I assume the `getEtags` query is returning no results for some reason. I can't think of another case that would cause Tasks.org to delete everything.

@Nurtyll if you create a new collection and add a single task do you experience the same behavior?

**Comment by Nurtyll** [comment]
Hi all!

> @Nurtyll can you update Tasks.org to v11.2.1 and try again? Prior to this version Tasks wasn't displaying error messages for EteSync app sync. After updating and attempting to sync there will be an error indicator in the navigation drawer if there was an exception

I installed the new version - no change in behaviour and no error message.

> @Nurtyll if you create a new collection and add a single task do you experience the same behavior?

I created a new list and added a task and forced several syncs inside etesync and tasks.org - right now the task is visible. So far the tasks always disappeared after a certain time, I'll keep you updated.

Right now one task inside the existing lists, which I edited inside the web interface (https://pim.etesync.com) is also visible inside the tasks.org app (note that the other tasks are not visible...)

Thank you all for your persistence and help!

**Comment by tasn** [comment]
I'm still puzzled as to what's going on.

**Comment by abaker** [comment]
Yeah I still have no idea what is going on. I was curious whether this affected only lists migrated from v1 or if it also affected new lists (don't know why that would make a difference, just guessing).

**Comment by Nurtyll** [comment]
Strangely enough, both tasks have now disappeared: the one updated via web gui and the other testtask inside the new testlist.
I can only see the local tasks now...

**Comment by tasn** [comment]
Damn. :(
Do you still have OpenTasks installed? Or did you remove it after we chatted?

**Comment by Nurtyll** [comment]
No, I only have tasks.org installed. I had OpenTasks only installed for a view minutes - just for testing reasons.

**Comment by Nurtyll** [comment]
Since yesterday evening, it effects calender entries too. Everything gone, except the entries I made recently inside the web app...

Could it be a problem with my android version ( Fairphone Open 19.11.2, Android 7.1.2)? Because I can't figure why no one other seems to have the issue and Faorphones are not that much on the market compared to other brands.

Have a nice weekend!

**Comment by Nurtyll** [comment]
Do you know if there is a way to log into the web app via Firefox mobile on Android?  I get an error messag saying "invalid usage".

**Comment by Nurtyll** [comment]
Any news?

**Comment by tasn** [comment]
Sorry for the delay, it's hard to always get to everything in a timely manner.

I don't know what issue you are experiencing on Firefox mobile, though it should definitely work. Does it work if you use an alternative browser? What about trying to log in from the desktop (web)?

A brute force workaround could be to remove your etesync account from the app and add it again in order to force a refresh. I really have no idea though why it would stop showing the data on Android.

**Comment by Nurtyll** [comment]
Ok this is quite a puzzle for me. Three days ago I changed the OS to [lineageOS for microG](https://lineage.microg.org/), installed etesync and tasks.org and since then everything works smoothly....

Thank you all for your perseverance and help. Have a wonderful weekend!
